version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/facade
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Prod12
      JWT_SECRET: TmYyb2w2W1zk9Pr4cVZfRg23IccH6AfPqjSO2NeT2BfU3ZYztZmOouQEKtmn4dI6JZwK64V1wTXI+4qTwLHD7g==
      SPRING_APPLICATION_NAME: facede
      SERVER_PORT: 8081
    networks:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: facade
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Prod12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
